
services:

  database:
    image: neo4j:5.23.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/StrongPsPsP5
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

  test:
    build:
      context: ../../
      dockerfile: docker/integration_tests/dockerfile
    depends_on:
      - database
    links:
      - database
    container_name: ragger
    environment:
      - SSL_CERT_DIR=/etc/ssl/certs
    command: > 
      bash -c "python3 -m pytest ./test/integration_tests || exit 1" 
      && docker-compose down
