FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

CMD ["bash"]

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN pip3 install torch --index-url https://download.pytorch.org/whl/cpu

COPY ./requirements /ragger/requirements
WORKDIR /ragger
RUN pip install -r requirements/test.txt
COPY . /ragger
