name: Test

on: [push]

jobs:
  build:
    name: Build DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose -f ./docker/build_dev/docker-compose.yml build

      - name: Build package
        run: docker compose -f ./docker/build_dev/docker-compose.yml up --abort-on-container-exit

  unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: docker compose -f ./docker/unit_tests/docker-compose.yml build

      - name: Run tests
        run: docker compose -f ./docker/unit_tests/docker-compose.yml up --abort-on-container-exit

  integration_test:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: docker compose -f ./docker/integration_tests/docker-compose.yml build

      - name: Run tests
        run: docker compose -f ./docker/integration_tests/docker-compose.yml up --abort-on-container-exit
